services:
  - type: web
    name: ctrlexpense-api
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn expense_tracker.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: "*"